package nl.codefield.ai_scheduler.service;

import nl.codefield.ai_scheduler.model.Address;
import nl.codefield.ai_scheduler.model.BarberType;
import nl.codefield.ai_scheduler.model.Company;

import java.util.List;
import java.util.UUID;

public class CompanyTestData {

    public static List<Company> createMockCompanies() {
        return List.of(
                // ==================== HEEMSKERK (5) ====================
                Company.builder()
                        .name("JEFF ROOZE Barbers & Academy")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("74839201")
                        .workRadius(15)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Jan van Scorelstraat")
                                .number("20")
                                .postalCode("1961 EZ")
                                .city("Heemskerk")
                                .latitude(52.51014)
                                .longitude(4.67389)
                                .build())
                        .build(),

                Company.builder()
                        .name("Barber Bekker")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("62940183")
                        .workRadius(20)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Deutzstraat")
                                .number("33")
                                .postalCode("1961 NS")
                                .city("Heemskerk")
                                .latitude(52.50982)
                                .longitude(4.66981)
                                .build())
                        .build(),

                Company.builder()
                        .name("Sultan Kapsalon")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("81039482")
                        .workRadius(10)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Kerkplein")
                                .number("5")
                                .postalCode("1961 EA")
                                .city("Heemskerk")
                                .latitude(52.51112)
                                .longitude(4.67104)
                                .build())
                        .build(),

                Company.builder()
                        .name("MODERNBARBER")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("53920184")
                        .workRadius(25)
                        .barberType(BarberType.HOUSE_CALL)
                        .address(Address.builder()
                                .street("Doctor Prinsengalerij")
                                .number("2")
                                .postalCode("1962 PR")
                                .city("Heemskerk")
                                .latitude(52.51310)
                                .longitude(4.67815)
                                .build())
                        .build(),

                Company.builder()
                        .name("Kapperij De Passage")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("39201847")
                        .workRadius(12)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Doctor Prinsengalerij")
                                .number("14")
                                .postalCode("1962 PR")
                                .city("Heemskerk")
                                .latitude(52.51313)
                                .longitude(4.67827)
                                .build())
                        .build(),

                // ==================== BEVERWIJK (5) ====================
                Company.builder()
                        .name("Thomas Barbershop")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("90182736")
                        .workRadius(30)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Baanstraat")
                                .number("2")
                                .postalCode("1942 CJ")
                                .city("Beverwijk")
                                .latitude(52.48625)
                                .longitude(4.65682)
                                .build())
                        .build(),

                Company.builder()
                        .name("Barbers On Tour")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("47382910")
                        .workRadius(15)
                        .barberType(BarberType.HOUSE_CALL)
                        .address(Address.builder()
                                .street("Koningstraat")
                                .number("23")
                                .postalCode("1941 BA")
                                .city("Beverwijk")
                                .latitude(52.47954)
                                .longitude(4.65412)
                                .build())
                        .build(),

                Company.builder()
                        .name("Kapsalon AYHAM")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("18273645")
                        .workRadius(20)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Raadhuisstraat")
                                .number("1A")
                                .postalCode("1941 EB")
                                .city("Beverwijk")
                                .latitude(52.48201)
                                .longitude(4.65547)
                                .build())
                        .build(),

                Company.builder()
                        .name("Dunya Hair Care")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("29384756")
                        .workRadius(40)
                        .barberType(BarberType.HOUSE_CALL)
                        .address(Address.builder()
                                .street("Parallelweg")
                                .number("128 A16")
                                .postalCode("1948 NN")
                                .city("Beverwijk")
                                .latitude(52.47890)
                                .longitude(4.66450)
                                .build())
                        .build(),

                Company.builder()
                        .name("Kapsalon Overloop")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("76543210")
                        .workRadius(15)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Wijkerbaan")
                                .number("19")
                                .postalCode("1945 SC")
                                .city("Beverwijk")
                                .latitude(52.49312)
                                .longitude(4.66210)
                                .build())
                        .build(),

                // ==================== CASTRICUM (5) ====================
                Company.builder()
                        .name("De Bakkumse Barbier")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("88392014")
                        .workRadius(15)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Burgemeester Mooijstraat")
                                .number("30")
                                .postalCode("1901 ET")
                                .city("Castricum")
                                .latitude(52.54890)
                                .longitude(4.66315)
                                .build())
                        .build(),

                Company.builder()
                        .name("Your Rockabilly Barber")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("49201834")
                        .workRadius(25)
                        .barberType(BarberType.HOUSE_CALL)
                        .address(Address.builder()
                                .street("Dorpsstraat")
                                .number("36B")
                                .postalCode("1901 EL")
                                .city("Castricum")
                                .latitude(52.54712)
                                .longitude(4.66480)
                                .build())
                        .build(),

                Company.builder()
                        .name("Mancave Barbers")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("30194827")
                        .workRadius(20)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Overtoom")
                                .number("1 A")
                                .postalCode("1901 EW")
                                .city("Castricum")
                                .latitude(52.54992)
                                .longitude(4.65588)
                                .build())
                        .build(),

                Company.builder()
                        .name("Barbershop Dawo")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("71839205")
                        .workRadius(15)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Dorpsstraat")
                                .number("31")
                                .postalCode("1901 EH")
                                .city("Castricum")
                                .latitude(52.54701)
                                .longitude(4.66512)
                                .build())
                        .build(),

                Company.builder()
                        .name("Armin Kapper")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("62948103")
                        .workRadius(10)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Kooiplein")
                                .number("12a")
                                .postalCode("1901 VW")
                                .city("Castricum")
                                .latitude(52.55110)
                                .longitude(4.67490)
                                .build())
                        .build(),

                // ==================== UITGEEST (5) ====================
                Company.builder()
                        .name("Haarmode Monique")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("29384102")
                        .workRadius(15)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Middelweg")
                                .number("22")
                                .postalCode("1911 EG")
                                .city("Uitgeest")
                                .latitude(52.52981)
                                .longitude(4.71120)
                                .build())
                        .build(),

                Company.builder()
                        .name("Kapsalon de Boet")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("48392015")
                        .workRadius(20)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Westergeest")
                                .number("46")
                                .postalCode("1911 AH")
                                .city("Uitgeest")
                                .latitude(52.52735)
                                .longitude(4.70412)
                                .build())
                        .build(),

                Company.builder()
                        .name("Trend Hair Uitgeest")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("71039485")
                        .workRadius(10)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Langebuurt")
                                .number("31")
                                .postalCode("1911 AR")
                                .city("Uitgeest")
                                .latitude(52.52890)
                                .longitude(4.70845)
                                .build())
                        .build(),

                Company.builder()
                        .name("Hair & Beauty Salon Jinny")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("62940174")
                        .workRadius(25)
                        .barberType(BarberType.HOUSE_CALL)
                        .address(Address.builder()
                                .street("Melkmarkt")
                                .number("4")
                                .postalCode("1911 BE")
                                .city("Uitgeest")
                                .latitude(52.52945)
                                .longitude(4.71005)
                                .build())
                        .build(),

                Company.builder()
                        .name("Kapper Studio 11")
                        .publicId(UUID.randomUUID().toString())
                        .kvkNumber("18273650")
                        .workRadius(12)
                        .barberType(BarberType.SHOP)
                        .address(Address.builder()
                                .street("Prinses Beatrixlaan")
                                .number("11")
                                .postalCode("1911 GD")
                                .city("Uitgeest")
                                .latitude(52.53120)
                                .longitude(4.71540)
                                .build())
                        .build()
        );
    }
}

