# ----------------------------------------------------
# To insert data`
# ----------------------------------------------------
# 1. Enable SQL initialization (always ensures it runs, even for non-embedded DBs)
spring.sql.init.mode=always

# 2. Point to your custom SQL script location(s)
spring.sql.init.data-locations=classpath:sql/cleanup.sql,classpath:sql/address_and_company_inserts.sql

# 3. (Optional) If you use Hibernate DDL auto-generation, make sure it happens BEFORE scripts run
spring.jpa.defer-datasource-initialization=true

#spring.jpa.hibernate.ddl-auto=create-drop